# Generated by Django 5.0 on 2025-01-07 05:52

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blog_alter_subscription_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='tipo',
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensual', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='pais',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
